esp_toml_version = 1.0

firmware_images_url = "https://yuyirobot.github.io/images/"

supported_apps = ["xiaozhi-tank", "xiaozhi-sparkbot-tank"]


[xiaozhi-tan]
chipsets = ["ESP32", "ESP32-S2", "ESP32-C3"]
image.esp32 = "xiaozhi-tank.bin"
image.esp32-s2 = "xiaozhi-tank.bin"
image.esp32-c3 = "xiaozhi-tank.bin"
android_app_url = "https://play.google.com/store/apps/details?id=com.espressif.rainmaker"
ios_app_url = "https://apps.apple.com/app/esp-rainmaker/id1497491540"

[xiaozhi-sparkbot-tank]
chipsets = ["ESP32", "ESP32-S2", "ESP32-C3"]
image.esp32 = "xiaozhi-sparkbot-tank.bin"
image.esp32-s2 = "xiaozhi-sparkbot-tank.bin"
image.esp32-c3 = "xiaozhi-sparkbot-tank.bin"
android_app_url = "https://play.google.com/store/apps/details?id=com.espressif.rainmaker"
ios_app_url = "https://apps.apple.com/app/esp-rainmaker/id1497491540"
